# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e02c751bb4d0cb0c48df21453e4b3adc3d6877277bc7edbe8e7d8812b2e6dce8ec8189fcb50e64737c91206b3cef37b67789b6f8a8772bd25946d6c15ee72e0

test:
  secret_key_base: 7c514860394dbaed1b4f328ca8d2818b6b054586a8c72c9158582ebc5209fae3f3ef4eeadb4b0702d095c10c93f97ea172e42d0f455837921ae59e6102a74740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
